# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('key', models.CharField(db_column='key', max_length=200, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
