# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_kvstore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KVStore',
            new_name='thumbnail_kvstore',
        ),
    ]
